# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://andrewm4894.github.io/am4894hubspot/"

git_url = "https://github.com/andrewm4894/am4894hubspot/tree/master/"

def custom_doc_links(name): return None
